### ISSUE TITLE
博主你好，我的后台管理系统登录界面打开的验证码是加载失败的

### ISSUE THREAD

**Issue by mengxiongtaiyi** [COLORREF/DjangoCourseDesign#1]
![Uploading Snipaste_2024-04-13_14-27-59.png…]()

**Comment by COLORREF** [comment]
你好，我更新了readme可以看一下，之前写的不太详细

**Comment by COLORREF** [comment]
安装PIL库同时修改一下字体文件的绝对路径（详细见readme），即可解决问题。
